const ACTION_TYPES = {
  ADD_TO_SHOP: "ADD_TO_SHOP",
  REMOVE_TO_SHOP: "REMOVE_TO_SHOP",
  ADD_TO_LIKE: "ADD_TO_LIKE",
  REMOVE_TO_LIKE: "REMOVE_TO_LIKE",
  SET_USER: "SET_USER",
  REMOVE_STORE:"REMOVE_STORE",
  ERROR:"ERROR"
}
    
export default ACTION_TYPES;